# Generated by Django 5.1.2 on 2024-10-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codencoit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='icon',
            field=models.ImageField(upload_to='industry_icon/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project_pic/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='clint_picture',
            field=models.ImageField(upload_to='client_pic/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ImageField(upload_to='service_icon/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='team_member/'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='icon',
            field=models.ImageField(upload_to='tech_icon/'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='picture',
            field=models.ImageField(upload_to='tech_pic/'),
        ),
    ]
