# Generated by Django 5.1.2 on 2024-10-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codencoit', '0002_alter_industry_icon_alter_projectimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='short_describtion',
            new_name='short_description',
        ),
    ]
