# Generated by Django 5.1.2 on 2024-10-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codencoit', '0003_rename_short_describtion_industry_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='clinet_name',
            field=models.CharField(default='fahmid', max_length=255),
            preserve_default=False,
        ),
    ]
