# Generated by Django 5.1.2 on 2024-10-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codencoit', '0004_projects_clinet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='clinet_name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='clint_picture',
            new_name='client_picture',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='clint_statement',
            new_name='client_statement',
        ),
    ]
