# Generated by Django 5.1.2 on 2024-10-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codencoit', '0005_rename_clinet_name_projects_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='long_describtion',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='short_describtion',
            new_name='short_description',
        ),
    ]
